name: Lint & prettier!

on:
  push:
  pull_request:

jobs:
  deploy:
    name: 'Deploy to Netlify'
    uses: jsmrcaga/action-netlify-deploy@v1.1.0
    with:
      NETLIFY_AUTH_TOKEN: ewfwefw
      NETLIFY_DEPLOY_TO_PROD: true
