name: Lint & prettier!

on:
  push:
  pull_request:

jobs:
  deploy:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
